/// <reference types="vite/client" />

// WASM pkg module — generated by wasm-bindgen, loaded via @wasm alias
declare module '@wasm/wasm_lib.js' {
  export function parse_csv(csv: string): unknown
  export function deep_equal(a: unknown, b: unknown): boolean
  export function sort_by_key(data: unknown, key: string): unknown
  export function find_vanity_batch(
    prefix: string,
    suffix: string,
    case_sensitive: boolean,
    batch_size: number
  ): string | null
  export function validate_vanity_input(prefix: string, suffix: string): string | null
  export function estimate_attempts(
    prefix_len: number,
    suffix_len: number,
    case_sensitive: boolean
  ): number
  export function health_check(): string
  export function get_version(): string
}

declare module '*.module.css' {
  const classes: { readonly [key: string]: string }
  export default classes
}

declare module '*.css' {
  const css: string
  export default css
}

declare module '*.wasm' {
  const wasmModule: WebAssembly.Module
  export default wasmModule
}

declare module '*?worker' {
  const WorkerFactory: new () => Worker
  export default WorkerFactory
}

declare module '*.png' {
  const value: string
  export default value
}

declare module '*.jpg' {
  const value: string
  export default value
}

declare module '*.svg' {
  const value: string
  export default value
}

interface ImportMetaEnv {
  readonly VITE_APP_TITLE: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
